#include "SPSocietySimulationComponent.h"

#if WITH_DEV_AUTOMATION_TESTS
#include "Kismet/GameplayStatics.h"
#include "Misc/AutomationTest.h"
#include "UObject/UObjectGlobals.h"

IMPLEMENT_SIMPLE_AUTOMATION_TEST(FSPSocietySourceParityTest,
    "SpacePatriot.Society.SourceParity",
    EAutomationTestFlags::EditorContext | EAutomationTestFlags::EngineFilter)

bool FSPSocietySourceParityTest::RunTest(const FString& Parameters)
{
    USPSocietySimulationComponent* First = NewObject<USPSocietySimulationComponent>(GetTransientPackage());
    USPSocietySimulationComponent* Second = NewObject<USPSocietySimulationComponent>(GetTransientPackage());
    if (!TestTrue(TEXT("catalog initializes"), First->InitializeSociety(false)) ||
        !TestTrue(TEXT("second catalog initializes"), Second->InitializeSociety(false))) return false;

    TestEqual(TEXT("all original worlds have markets"), First->State->Markets.Num(), 19);
    TestEqual(TEXT("all original settlements are present"), First->State->Settlements.Num(), 420);
    TestEqual(TEXT("persistent residents match source seeding"), First->State->Residents.Num(), 4052);
    const FString CityId = TEXT("earth:city:0");
    const FString WorldId = TEXT("earth");
    FSPSocietySettlement City;
    TestTrue(TEXT("stable primary city ID resolves"), First->GetSettlement(CityId, City));
    TestEqual(TEXT("primary city's world"), City.WorldId, WorldId);

    const int32 StartCredits = First->State->PlayerCredits;
    const int32 StartStaged = First->GetStagedCargo(CityId, TEXT("ore"));
    const int32 StartHold = First->State->HoldOre;
    TestTrue(TEXT("purchase stages market cargo"), First->BuyAtSettlement(CityId, TEXT("ore"), 1));
    TestEqual(TEXT("purchase debits player"), First->State->PlayerCredits < StartCredits, true);
    TestEqual(TEXT("one unit staged"), First->GetStagedCargo(CityId, TEXT("ore")), StartStaged + 1);
    TestTrue(TEXT("physical load moves dock cargo into hold"), First->TransferCargo(CityId, TEXT("ore"), 1, true));
    TestEqual(TEXT("hold gains one unit"), First->State->HoldOre, StartHold + 1);
    TestEqual(TEXT("dock loses the same unit"), First->GetStagedCargo(CityId, TEXT("ore")), StartStaged);
    TestTrue(TEXT("physical unload returns unit to dock"), First->TransferCargo(CityId, TEXT("ore"), 1, false));
    TestEqual(TEXT("unloaded hold is restored"), First->State->HoldOre, StartHold);
    TestFalse(TEXT("cannot load unstaged cargo"), First->TransferCargo(CityId, TEXT("ore"), 2, true));

    First->AdvanceSimulation(600.0f);
    Second->AdvanceSimulation(600.0f);
    TestEqual(TEXT("fixed-step simulation advances exactly 600 seconds"), First->State->SimulationTime, 600.0);
    TestEqual(TEXT("market count survives advancement"), First->State->Markets.Num(), 19);
    TestEqual(TEXT("resident count survives advancement"), First->State->Residents.Num(), 4052);
    TestTrue(TEXT("city jobs generated by real service conditions"), First->State->Jobs.Num() > 0);
    TestTrue(TEXT("residents make off-screen decisions"), First->State->Residents.ContainsByPredicate([](const FSPResidentRecord& Resident)
    {
        return Resident.Visits > 0 || Resident.Deliveries > 0;
    }));
    TestTrue(TEXT("deterministic story news is generated"), First->State->News.Num() > 0);
    TestEqual(TEXT("same seeded simulation has same first resident itinerary"), First->State->Residents[0].Activity, Second->State->Residents[0].Activity);
    TestEqual(TEXT("same seeded simulation has same story count"), First->State->News.Num(), Second->State->News.Num());
    if (!First->State->News.IsEmpty() && !Second->State->News.IsEmpty())
        TestEqual(TEXT("same seeded simulation has same first story"), First->State->News[0].Summary, Second->State->News[0].Summary);
    TestTrue(TEXT("physical transaction stays local to first simulation"), First->State->PlayerCredits < Second->State->PlayerCredits);

    const FString ResidentId = First->State->Residents[0].Id;
    FSPResidentRecord Before;
    TestTrue(TEXT("resident ID resolves before life restart"), First->GetResident(ResidentId, Before));
    TestTrue(TEXT("life can restart on a world without actors"), First->RestartResidentLife(ResidentId));
    FSPResidentRecord After;
    TestTrue(TEXT("resident ID remains stable after restart"), First->GetResident(ResidentId, After));
    TestEqual(TEXT("new life increments generation"), After.Life, Before.Life + 1);
    FString ContractText;
    TestTrue(TEXT("named citizen exposes source contract"), First->RequestNamedContract(TEXT("earth-resident-1"), ContractText));
    TestTrue(TEXT("named contract retains specific request"), ContractText.Contains(TEXT("Six alloy")));
    TestTrue(TEXT("alloy can enter player inventory"), First->AddPlayerSupply(TEXT("alloy"), 6));
    TestTrue(TEXT("named contract consumes supply and pays reward"), First->FulfillNamedContract(TEXT("earth-resident-1"), CityId));
    TestEqual(TEXT("named contract spends alloy"), First->GetPlayerSupply(TEXT("alloy")), 0);
    TestEqual(TEXT("named contract grants ammunition"), First->GetRifleReserve(), 30);
    TestFalse(TEXT("named contract cannot be paid twice"), First->FulfillNamedContract(TEXT("earth-resident-1"), CityId));
    TestFalse(TEXT("invalid goods cannot be bought"), First->BuyAtSettlement(CityId, TEXT("magic"), 1));
    TArray<uint8> Serialized;
    TestTrue(TEXT("actor-free society serializes to a save buffer"), UGameplayStatics::SaveGameToMemory(First->State, Serialized));
    TestTrue(TEXT("full 420-city society stays below an 8 MiB save budget"), Serialized.Num() > 0 && Serialized.Num() < 8 * 1024 * 1024);
    return true;
}
#endif
